---
- name: Configure Celestia node
  shell: |
    source $HOME/.bash_profile
    celestia-appd config keyring-backend os
    celestia-appd config chain-id {{ celestia_chain_id }}
  args:
    executable: /bin/bash
  become: false
