---
- name: Configure pruning
  shell: |
    sed -i -e "s/^pruning *=.*/pruning = 'custom'/" $HOME/.celestia-app/config/app.toml
    sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = '100'/" $HOME/.celestia-app/config/app.toml
    sed -i -e "s/^pruning-interval *=.*/pruning-interval = '50'/" $HOME/.celestia-app/config/app.toml
  args:
    executable: /bin/bash
  become: false
