---
- name: Create Celestia systemd service file
  copy:
    dest: /etc/systemd/system/celestia-appd.service
    content: |
      [Unit]
      Description=Celestia node
      After=network-online.target
      [Service]
      User={{ ansible_user }}
      WorkingDirectory=$HOME/.celestia-app
      ExecStart=$(which celestia-appd) start --home $HOME/.celestia-app
      Restart=on-failure
      RestartSec=5
      LimitNOFILE=65535
      [Install]
      WantedBy=multi-user.target
  become: true
