---
- name: Download Celestia binary
  shell: |
    cd $HOME
    rm -rf celestia-app
    git clone https://github.com/celestiaorg/celestia-app.git
    cd celestia-app/
    git checkout tags/{{ app_version }} -b {{ app_version }}
    make install
  args:
    executable: /bin/bash
  become: false
