---
- name: Set seeds and peers
  shell: |
    sed -i -e "/^\[p2p\]/,/^\[/{s/^[[:space:]]*seeds *=.*/seeds = '{{ seeds }}'/}" \
           -e "/^\[p2p\]/,/^\[/{s/^[[:space:]]*persistent_peers *=.*/persistent_peers = '{{ peers }}'/}" \
           $HOME/.celestia-app/config/config.toml
  args:
    executable: /bin/bash
  become: false
