---
- name: Clean up existing Celestia node directory
  shell: rm -rf $HOME/celestia-node
  args:
    executable: /bin/bash
  become: false

- name: Clone Celestia bridge node repository
  git:
    repo: https://github.com/celestiaorg/celestia-node.git
    dest: "{{ ansible_env.HOME }}/celestia-node"
    version: "tags/{{ bridge_version }}"
  become: false

- name: Build and install Celestia bridge node
  shell: |
    cd $HOME/celestia-node
    make build
    sudo make install
    make cel-key
  args:
    executable: /bin/bash
  become: false
