---
- name: Download Go binary
  shell: |
    cd $HOME
    wget "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
    sudo rm -rf /usr/local/go
    sudo tar -C /usr/local -xzf "go{{ go_version }}.linux-amd64.tar.gz"
    rm "go{{ go_version }}.linux-amd64.tar.gz"
  args:
    executable: /bin/bash

- name: Create .bash_profile if not present
  file:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    state: touch
    mode: '0644'

- name: Add Go binary to PATH in .bash_profile
  lineinfile:
    dest: ~/.bash_profile
    line: "export PATH=$PATH:/usr/local/go/bin:~/go/bin"
    state: present

- name: Ensure ~/go/bin directory exists
  file:
    path: ~/go/bin
    state: directory
