---
- name: Download Golang {{ go_version }}
  ansible.builtin.get_url:
    url: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"

- name: Remove existing Go installation
  ansible.builtin.file:
    path: "/usr/local/go"
    state: absent

- name: Extract Golang to /usr/local
  ansible.builtin.unarchive:
    src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/usr/local"
    remote_src: yes

- name: Remove Go tarball
  ansible.builtin.file:
    path: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    state: absent

- name: Create .bash_profile if it does not exist for the remote user
  become: yes
  become_user: "{{ ansible_ssh_user | default(ansible_env.USER) }}"  # Use ansible_ssh_user or fallback to system user
  ansible.builtin.file:
    path: "/home/{{ ansible_ssh_user | default(ansible_env.USER) }}/.bash_profile"
    state: touch
    mode: '0644'

- name: Ensure Go binary path is in the remote user's .bash_profile
  become: yes
  become_user: "{{ ansible_ssh_user | default(ansible_env.USER) }}"  # Use ansible_ssh_user or fallback to system user
  ansible.builtin.lineinfile:
    dest: "/home/{{ ansible_ssh_user | default(ansible_env.USER) }}/.bash_profile"
    line: 'export PATH=$PATH:/usr/local/go/bin:/home/{{ ansible_ssh_user | default(ansible_env.USER) }}/go/bin'
    state: present

- name: Source .bash_profile and check Go version
  become: yes
  become_user: "{{ ansible_ssh_user | default(ansible_env.USER) }}"  # Use ansible_ssh_user or fallback to system user
  shell: |
    source /home/{{ ansible_ssh_user | default(ansible_env.USER) }}/.bash_profile
    go version
  args:
    executable: /bin/bash
  register: go_version_output
  failed_when: "'go version' not in go_version_output.stdout"

- name: Print Go version
  debug:
    msg: "{{ go_version_output.stdout }}"
