---
- name: Configure Celestia node
  shell: |
    source /etc/profile.d/go.sh
    celestia-appd config keyring-backend os
    celestia-appd config chain-id {{ celestia_chain_id }}
  args:
    executable: /bin/bash
  become: false
