---
- name: Create celestia-appd systemd service
  ansible.builtin.template:
    src: celestia-appd.service.j2
    dest: /etc/systemd/system/celestia-appd.service
  become: true

- name: Reload systemd to apply new service
  ansible.builtin.systemd:
    daemon_reload: yes