- name: Ensure Celestia bridge node repository is present
  git:
    repo: https://github.com/celestiaorg/celestia-node.git
    dest: "/home/{{ ansible_user }}/celestia-node"
    version: "tags/{{ bridge_version }}"
  become: no  # Don't escalate privileges to root
