---
- name: Install and configure Celestia Bridge Node
  hosts: bridge
  become: yes
  vars:
    go_version: "1.23.0"
    bridge_version: "v0.16.0"
    rpc_node_ip: ""  # Replace with the actual RPC node IP
  tasks:
    - name: Install Go Lang
      import_role:
        name: install_go
    - include_tasks: roles/bridge_node/cleanup_celestia.yml
    - include_tasks: roles/bridge_node/clone_celestia_repo.yml
    - include_tasks: roles/bridge_node/build_and_install_celestia.yml
    - include_tasks: roles/bridge_node/initialize_bridge_node.yml
    - include_tasks: roles/bridge_node/create_systemd_service.yml
    - include_tasks: roles/bridge_node/reload_systemd.yml
    - include_tasks: roles/bridge_node/start_bridge_service.yml