---
- name: Install and configure Celestia Bridge Node
  hosts: bridge
  become: yes
  vars:
    go_version: "1.23.0"
    bridge_version: "v0.16.0"
    rpc_node_ip: "172.16.0.109"  # Replace with the actual RPC node IP
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes

    - name: Install required system packages
      apt:
        name:
          - curl
          - git
          - wget
          - htop
          - tmux
          - build-essential
          - jq
          - make
          - gcc
          - tar
          - clang
          - pkg-config
          - libssl-dev
          - ncdu
        state: present
    - name: Install Go Lang
      include_role:
        name: install_go

    - name: Clean up existing Celestia app directory
      include_role:
        name: bridge_node
        tasks_from: cleanup_celestia.yml

    - name: Clone Celestia repository
      include_role:
        name: bridge_node
        tasks_from: clone_celestia_repo.yml

    - name: Build and install Celestia bridge node
      include_role:
        name: bridge_node
        tasks_from: build_and_install_celestia.yml

    - name: Initialize Celestia bridge node
      include_role:
        name: bridge_node
        tasks_from: initialize_bridge_node.yml

    - name: Create Celestia bridge systemd service
      include_role:
        name: bridge_node
        tasks_from: create_systemd_service.yml

    - name: Reload systemd
      include_role:
        name: bridge_node
        tasks_from: reload_systemd.yml