---
- name: Quick Sync Celestia Node
  hosts: all
  become: yes
  tasks:

    - name: Remove existing Celestia app data
      file:
        path: "{{ ansible_env.HOME }}/.celestia-app/data"
        state: absent

    - name: Recreate Celestia app data directory
      file:
        path: "{{ ansible_env.HOME }}/.celestia-app/data"
        state: directory
        mode: '0755'

    - name: Get the latest snapshot name
      shell: |
        SNAP_NAME=$(curl -s https://snaps.qubelabs.io/celestia/ | egrep -o ">mocha-4.*tar" | tr -d ">")
        echo $SNAP_NAME
      register: snap_name

    - name: Download Celestia snapshot using aria2c
      ansible.builtin.command:
        cmd: "aria2c -x 16 -s 16 -o celestia-snap.tar https://snaps.qubelabs.io/celestia/{{ snap_name.stdout }}"
        chdir: "{{ ansible_env.HOME }}"
      args:
        creates: "{{ ansible_env.HOME }}/celestia-snap.tar"

    - name: Extract the snapshot to Celestia app data folder
      ansible.builtin.unarchive:
        src: "{{ ansible_env.HOME }}/celestia-snap.tar"
        dest: "{{ ansible_env.HOME }}/.celestia-app/data"
        remote_src: yes
