---
- name: Upgrade Celestia Bridge Node
  hosts: bridge-node-servers
  become: yes
  tasks:

    - name: Stop Celestia Bridge service
      shell: sudo systemctl stop celestia-bridge
      args:
        executable: /bin/bash
      become: yes

    - include_tasks: roles/bridge_node/clone_celestia_repo.yml
    - include_tasks: roles/bridge_node/build_and_install_celestia.yml
    
    - name: Update Celestia bridge configuration
      shell: celestia bridge config-update --p2p.network mocha
      args:
        executable: /bin/bash
      become: no

    - name: Restart Celestia Bridge service
      shell: sudo systemctl restart celestia-bridge
      args:
        executable: /bin/bash
      become: yes
