---
- name: Upgrade Celestia Bridge Node
  hosts: bridge-node-servers
  become: yes
  vars:
    bridge_version: "v0.20.0"
  tasks:

    - name: Stop Celestia Bridge service
      shell: sudo systemctl stop celestia-bridge
      args:
        executable: /bin/bash
      become: yes

    - name: Clone Celestia repository
      include_role:
        name: bridge_node
        tasks_from: clone_celestia_repo.yml

    - name: Build and install Celestia bridge node
      include_role:
        name: bridge_node
        tasks_from: build_and_install_celestia.yml

    - name: Update Celestia bridge configuration
      shell: celestia bridge config-update --p2p.network mocha
      args:
        executable: /bin/bash
      become: no

    - name: Restart Celestia Bridge service
      shell: sudo systemctl restart celestia-bridge
      args:
        executable: /bin/bash
      become: yes
